
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 28 2026 15:54:31 IST (Mar 28 2026 10:24:31 UTC)

// Verification Directory fv/trafficlight 

module trafficlight(clk, rst, LED_NS, LED_WE);
  input clk, rst;
  output [2:0] LED_NS, LED_WE;
  wire clk, rst;
  wire [2:0] LED_NS, LED_WE;
  wire [5:0] state;
  wire [3:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, n_1, n_2;
  wire n_3, n_4, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_47;
  SDFFSHQX1 \state_reg[0] (.SN (n_44), .CK (clk), .D (n_42), .SI
       (state[0]), .SE (n_43), .Q (state[0]));
  SDFFRHQX1 \state_reg[5] (.RN (n_44), .CK (clk), .D (n_41), .SI
       (state[5]), .SE (n_43), .Q (state[5]));
  SDFFRHQX1 \state_reg[3] (.RN (n_44), .CK (clk), .D (n_29), .SI
       (state[3]), .SE (n_43), .Q (state[3]));
  SDFFRHQX1 \state_reg[4] (.RN (n_44), .CK (clk), .D (n_34), .SI
       (state[4]), .SE (n_43), .Q (state[4]));
  SDFFRHQX1 \count_reg[1] (.RN (n_44), .CK (clk), .D (n_31), .SI
       (count[1]), .SE (n_43), .Q (count[1]));
  SDFFRHQX1 \count_reg[3] (.RN (n_44), .CK (clk), .D (n_37), .SI
       (count[3]), .SE (n_43), .Q (count[3]));
  SDFFRHQX1 \count_reg[0] (.RN (n_44), .CK (clk), .D (n_39), .SI
       (count[0]), .SE (n_43), .Q (count[0]));
  SDFFRHQX1 \count_reg[2] (.RN (n_44), .CK (clk), .D (n_36), .SI
       (count[2]), .SE (n_43), .Q (count[2]));
  SDFFRHQX1 \state_reg[1] (.RN (n_44), .CK (clk), .D (n_26), .SI
       (state[1]), .SE (n_43), .Q (state[1]));
  SDFFRHQX1 \state_reg[2] (.RN (n_44), .CK (clk), .D (n_23), .SI
       (state[2]), .SE (n_43), .Q (state[2]));
  TLATNXL \LED_WE_reg[0] (.GN (n_43), .D (n_11), .Q (LED_WE[0]), .QN
       (UNCONNECTED));
  TLATNXL \LED_WE_reg[1] (.GN (n_43), .D (n_17), .Q (LED_WE[1]), .QN
       (UNCONNECTED0));
  TLATNXL \LED_NS_reg[0] (.GN (n_43), .D (n_16), .Q (LED_NS[0]), .QN
       (UNCONNECTED1));
  TLATNXL \LED_NS_reg[2] (.GN (n_43), .D (n_6), .Q (LED_NS[2]), .QN
       (UNCONNECTED2));
  TLATNXL \LED_WE_reg[2] (.GN (n_43), .D (n_8), .Q (LED_WE[2]), .QN
       (UNCONNECTED3));
  TLATNXL \LED_NS_reg[1] (.GN (n_43), .D (n_19), .Q (LED_NS[1]), .QN
       (UNCONNECTED4));
  OAI21X1 g2122__2398(.A0 (n_40), .A1 (n_24), .B0 (n_38), .Y (n_42));
  MXI2XL g2123__5107(.A (n_40), .B (n_33), .S0 (n_32), .Y (n_41));
  AOI31X1 g2130__6260(.A0 (n_22), .A1 (n_30), .A2 (n_38), .B0
       (count[0]), .Y (n_39));
  NOR2XL g2132__4319(.A (n_21), .B (n_35), .Y (n_37));
  NOR2XL g2135__8428(.A (n_9), .B (n_35), .Y (n_36));
  MXI2XL g2120__5526(.A (n_33), .B (n_28), .S0 (n_32), .Y (n_34));
  AOI32X1 g2133__6783(.A0 (n_25), .A1 (n_30), .A2 (n_38), .B0 (n_47),
       .B1 (n_4), .Y (n_31));
  OAI22X1 g2121__3680(.A0 (n_28), .A1 (n_32), .B0 (n_13), .B1 (n_14),
       .Y (n_29));
  AND4XL g2137__1617(.A (n_40), .B (n_28), .C (n_18), .D (n_27), .Y
       (n_43));
  AND2XL g2138__2802(.A (n_27), .B (n_38), .Y (n_35));
  OAI21X1 g2139__1705(.A0 (n_15), .A1 (n_10), .B0 (n_25), .Y (n_26));
  CLKINVX1 g2129(.A (n_32), .Y (n_24));
  OAI21XL g2140__5122(.A0 (n_20), .A1 (n_22), .B0 (n_30), .Y (n_23));
  NAND2XL g2134__8246(.A (n_12), .B (n_21), .Y (n_32));
  NAND2XL g2141__7098(.A (n_20), .B (n_19), .Y (n_25));
  NOR2XL g2143__6131(.A (n_17), .B (n_16), .Y (n_18));
  NAND2XL g2145__1881(.A (n_15), .B (n_16), .Y (n_38));
  NAND2BX1 g2142__5115(.AN (n_14), .B (n_13), .Y (n_30));
  AND2X1 g2144__7482(.A (n_14), .B (n_22), .Y (n_27));
  XNOR2X1 g2136__4733(.A (count[3]), .B (n_12), .Y (n_21));
  INVXL g2147(.A (n_28), .Y (n_11));
  CLKINVX1 g2146(.A (n_10), .Y (n_16));
  INVXL g2148(.A (n_22), .Y (n_19));
  CLKINVX1 g2152(.A (n_33), .Y (n_17));
  MXI2XL g2153__6161(.A (n_2), .B (count[2]), .S0 (n_1), .Y (n_9));
  NAND4BXL g2149__9315(.AN (state[1]), .B (state[0]), .C (n_7), .D
       (n_8), .Y (n_10));
  NAND4BXL g2151__9945(.AN (state[0]), .B (state[1]), .C (n_8), .D
       (n_7), .Y (n_22));
  NAND4BXL g2150__2883(.AN (state[4]), .B (state[3]), .C (n_7), .D
       (n_6), .Y (n_28));
  NAND2BX1 g2159__2346(.AN (n_47), .B (n_3), .Y (n_13));
  NAND3BX1 g2160__1666(.AN (n_47), .B (count[2]), .C (count[3]), .Y
       (n_15));
  NAND4BXL g2154__7410(.AN (state[2]), .B (state[5]), .C (n_8), .D
       (n_6), .Y (n_40));
  NAND4BXL g2156__6417(.AN (state[3]), .B (state[4]), .C (n_7), .D
       (n_6), .Y (n_33));
  NAND4BXL g2155__5477(.AN (state[5]), .B (state[2]), .C (n_8), .D
       (n_6), .Y (n_14));
  NAND2BX1 g2157__2398(.AN (n_4), .B (n_3), .Y (n_20));
  NOR2XL g2158__5107(.A (n_2), .B (n_1), .Y (n_12));
  NAND2XL g2161__4319(.A (count[0]), .B (count[1]), .Y (n_1));
  NAND2BX1 g2164__8428(.AN (count[1]), .B (count[0]), .Y (n_4));
  NOR2XL g2162__5526(.A (state[2]), .B (state[5]), .Y (n_7));
  NOR2XL g2165__6783(.A (count[2]), .B (count[3]), .Y (n_3));
  NOR2XL g2163__3680(.A (state[3]), .B (state[4]), .Y (n_8));
  NOR2XL g2167__1617(.A (state[1]), .B (state[0]), .Y (n_6));
  INVXL g2168(.A (count[2]), .Y (n_2));
  INVXL g2169(.A (rst), .Y (n_44));
  NAND2BX1 g2(.AN (count[0]), .B (count[1]), .Y (n_47));
endmodule

